### ISSUE TITLE
Upgrade of cloudposse/ecs-container-definition/aws to 0.23.0 breaks additional env vars

### ISSUE THREAD

**Issue by parmouraly** [terraform-aws-modules/terraform-aws-atlantis#119] opened 2020-05-12 13:20 UTC
Version: `2.7.0`

### Context ### 
We've been using `terraform-aws-atlantis` for a while now and have been passing some additional environment variables like so (terragrunt):

```
custom_environment_variables = [
    "${map("name", "ATLANTIS_CHECKOUT_STRATEGY", "value", "merge")}",
    ...
  ]
```

### Problem ### 
It's been working fine up until version `2.6.0` included
After that, and with the upgrade of `cloudposse/ecs-container-definition/aws` to `0.23.0` the above code no longer works. Getting the following error:

```
Error: Invalid value for module argument
  on .terraform/modules/atlantis/main.tf line 436, in module "container_definition_github_gitlab":
 436:   environment = concat(
 437:     local.container_definition_environment,
 438:     var.custom_environment_variables,
 439:   )
The given value is not suitable for child module variable "environment"
defined at
.terraform/modules/atlantis.container_definition_github_gitlab/variables.tf:84,1-23:
element 9: object required.
```

### Expected behaviour ### 
No error should occur and `terraform-aws-atlantis` module should try to restore backwards compatibility or if this is not possible document the breaking change and maybe provide tips on how to migrate in release docs

**Comment by nitrocode** [comment] 2020-05-12 13:35
[Changes between v2.12.0 and v2.6.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/compare/v2.6.0...v2.12.0)

The module `container_definition_github_gitlab` that throws the error is sourced from `cloudposse/ecs-container-definition/aws` and has gone from `v0.15.0` to `v0.23.0`. I wonder if pinning that would solve the issue for now.

**Comment by antonbabenko** [comment] 2020-05-12 13:41
@nitrocode Thanks for the fast follow-up!

Apparently there were some changes in `cloudposse/ecs-container-definition/aws` and we need to adapt to them in this module. PR is welcome.

**Comment by parmouraly** [comment] 2020-05-12 13:47
Thanks both! 
I have pinned our version to `2.6.0` so not a pressing issue for us atm but wanted to open an issue here for traceability and because I know that more people will have hit similar issues with this upgrade.

Unless anybody else beats me to it I'll look into opening a PR when I get a moment.

**Comment by nitrocode** [comment] 2020-05-12 13:48
Workaround for now for me is to pin this down unfortunately. 

```
module "atlantis" {
  source  = "terraform-aws-modules/atlantis/aws"
  version = "== 2.6.0"
  ...
}
```

> Apparently there were some changes in `cloudposse/ecs-container-definition/aws` and we need to adapt to them in this module. PR is welcome.

I think if you break it, you bought it 😆 

@antonbabenko why were so many tags removed ? I feel like these last few releases, as well-intentioned as they were, may have regressed this module.

**Comment by antonbabenko** [comment] 2020-05-12 13:54
I don't control what is going on in `cloudposse/ecs-container-definition/aws`.

All I wanted to do was to update dependencies, merge many PRs, close some issues. I tested these as much as I could in several of my environments before the merge.

Let me revert deleted tags. It was probably related to an old branch which I didn't merge completely. I will fix it now.

**Comment by antonbabenko** [comment] 2020-05-12 14:09
[v2.14.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v2.14.0) has been released with fixed tags.

Here is the diff - https://github.com/terraform-aws-modules/terraform-aws-atlantis/compare/v2.6.0...v2.14.0

**Comment by antonbabenko** [comment] 2020-05-12 14:13
@parmouraly I can't reproduce the bug you have encountered when I specify `custom_environment_variables`.

Please make sure that you removed the cache `.terraform` folder.

**Comment by parmouraly** [comment] 2020-05-12 14:16
Pretty sure I did, but I'll try again. If you could share your code snippet for defining `custom_environment_variables` and how you pass them to the module that would be great.

**Comment by nitrocode** [comment] 2020-05-12 14:17
@parmouraly what version of terraform are you using ?

@antonbabenko Thanks! We definitely appreciate you maintaining this module for us.

One other thing is that the name changes of the terraform resources also require `terraform state mv` changes otherwise current ones are destroyed and recreated... Not a big deal but it would be nicer to keep the resource names since Terraform doesn't have an automated way of picking up those new names.

This one was destroyed without being recreated.

```
module.atlantis.aws_lb_listener_rule.redirect_http_to_https will be destroyed
```

Renamed I think
```
module.atlantis.module.alb.aws_lb.application_no_logs[0] will be destroyed
module.atlantis.module.alb.aws_lb.this[0] will be created
```

```
module.atlantis.module.alb.aws_lb_listener.frontend_http_tcp[0] will be created
module.atlantis.module.alb.aws_lb_listener.frontend_http_tcp_no_logs[0] will be destroyed
```

```
module.atlantis.module.alb.aws_lb_listener.frontend_https[0] will be created
module.atlantis.module.alb.aws_lb_listener.frontend_https_no_logs[0] will be destroyed
```

```
module.atlantis.module.alb.aws_lb_target_group.main[0] will be created
module.atlantis.module.alb.aws_lb_target_group.main_no_logs[0] will be destroyed
```
```
module.atlantis.module.atlantis_sg.aws_security_group_rule.computed_ingress_with_source_security_group_id[0] will be destroyed
module.atlantis.module.atlantis_sg.aws_security_group_rule.ingress_with_source_security_group_id[0] will be created
```

**Comment by antonbabenko** [comment] 2020-05-12 14:18
Here is my sample:

```terraform
  custom_environment_variables = [
    {
      name  = "ATLANTIS_1"
      value = "value2"
    },
    map("name", "b", "value", "d"),
    "${map("name", "ATLANTIS_CHECKOUT_STRATEGY", "value", "merge")}"
  ]
```

**Comment by parmouraly** [comment] 2020-05-12 14:21
@nitrocode terraform `0.12.18`. Also I'm using it via `terragrunt`, unsure whether that could interfere. All I know is it broke with the new version of the `atlantis` module but didn't dig too much
@antonbabenko thanks for sharing this. I will go back to my code at some point to test again then. pretty sure it's not a caching issue though but will doublecheck.

**Comment by antonbabenko** [comment] 2020-05-12 14:23
@nitrocode I described the changes in names in PR where they were introduced - https://github.com/terraform-aws-modules/terraform-aws-atlantis/pull/99#issuecomment-627206086 . I agree, it is rather invisible place for everyone who are not watching this repository closely.

@nitrocode This separate rule is not needed, because it is now part of the module, so it should have been recreated:
```
module.atlantis.aws_lb_listener_rule.redirect_http_to_https will be destroyed
```

**Comment by antonbabenko** [comment] 2020-05-12 14:26
@parmouraly I also use Atlantis with terragrunt. Make sure you delete all `.terragrunt-cache` folders in your project (if unsure).

**Comment by parmouraly** [comment] 2020-05-12 14:30
Yea same here. I got the error both locally (after manually removing my `.terragrunt-cache` folders and on `Atlantis` after restarting it and on separate PRs.. Anyway will doublecheck some time between today an tomorrow and get back to you.

**Comment by nitrocode** [comment] 2020-06-16 15:03
Finally got a chance to upgrade from `2.6.0` to `2.17.0`. I used the terraform state mv commands above and applied the terraform. Everything seems to be working as expected.

**Comment by antonbabenko** [comment] 2020-06-16 15:15
Closing this issue. Thanks for the confirmation, @nitrocode !

**Closed by antonbabenko** 2020-06-16 15:15 UTC
